### ISSUE TITLE
[기능] 레스토랑 DTO

### ISSUE THREAD

**Issue by ChanhyukPark-Tech** [toppingskorea/toppings-server#15]
레스토랑 상세조회시 isMine값이 필요합니다.
내가 아니라면 수정 및 삭제를 할 수 없기 떄문입니다

![image](https://user-images.githubusercontent.com/69495129/209786121-8f010e3c-77b5-4508-b8c5-a1ece3470a7c.png)

**Comment by k-gn** [comment]
해당 내용 추가했습니다~ 확인 감사합니다!
