### ISSUE TITLE
[이슈] 회원가입시

### ISSUE THREAD

**Issue by ChanhyukPark-Tech** [toppingskorea/toppings-server#17]
회원가입시 eatingHabits를 선택하지 않고 빈 배열로 보내면,
마이프로필접근시 유저정보 조회 api에서 에러가 발생합니다.

eatingHabits를 정상적으로 선택한 경우 에러가 발생하지 않습니다.

**Comment by k-gn** [comment]
habit validation 코드가 갑자기 사라졋네여 뭐 하다가 잘못 건드린듯해서 다시 추가하였습니당

**Comment by ChanhyukPark-Tech** [comment]
thx for your hard works
