### ISSUE TITLE
[이슈] 회원정보수정

### ISSUE THREAD

**Issue by ChanhyukPark-Tech** [toppingskorea/toppings-server#18]
https://user-images.githubusercontent.com/69495129/211339786-db10546c-3966-4220-8e20-647404de3748.mov

웹에서 eatingHabits을 바꾸면 프로필사진이 올바르지 않은 url로 바뀌어버리고, eatingHabits은 정작 바뀌지 않습니다.
포스트맨에서는수정이 잘됩니다..혹시 짐작가는부분있으신가요?

**Comment by k-gn** [comment]
![image](https://user-images.githubusercontent.com/77544214/211430143-ec86ff40-edf6-4be5-b25c-d54abed4f34a.png)

![image](https://user-images.githubusercontent.com/77544214/211430167-44fa2e44-4aa9-4bfc-8656-2a1492a9aa8f.png)

두 이미지를 보시면 habit 으로 요구하는데 habits 로 보내고 있어서 수정이 안되는 걸로 파악됩니당

추가로 profile 을 수정하지 않았을 경우 base64 가 아닌 기존 주소를 보내고 있어서 해당 검증 코드 추가하였습니다~

**Comment by chanhyukpark-29cm** [comment]
와...........이거떄문에 시간많이썼는데 매의 눈 감사합니다

>추가로 profile 을 수정하지 않았을 경우 base64 가 아닌 기존 주소를 보내고 있어서 해당 검증 코드 추가하였습니다~

와.. 이부분도 고민했었는데 대박 감사합니다
