### ISSUE TITLE
[기능개발] 프로필 eating Habit 있었다가 지우기

### ISSUE THREAD

**Issue by ChanhyukPark-Tech** [toppingskorea/toppings-server#20]
![image](https://user-images.githubusercontent.com/69495129/211545789-ecac8314-c7ed-4076-abfd-169873689b3c.png)

eatingHabit을 기존에 설정해둔사람인데 지우고 싶은경우 빈 배열을 보내려고 하는데 eating Habit이 지워지지 않습니다!

**Comment by k-gn** [comment]
수정했습니다! 확인 부탁드립니다~

**Comment by ChanhyukPark-Tech** [comment]
https://github.com/toppingskorea/toppings-server/commit/a793ec3503ea2a9969538731ac751dedbecb742c
