### ISSUE TITLE
[이슈] 관리자 CORS 에러를 해결합니다.

### ISSUE THREAD

**Issue by ChanhyukPark-Tech** [toppingskorea/toppings-server#24]
admin.toppings.co.kr 에서 API쏘면 CORS 에러가 발생합니다.

![image](https://user-images.githubusercontent.com/69495129/212382035-f80fc7d9-19cf-41d2-984e-72ed65cb6999.png)

해결해주시면 감사하겠습니다!

**Comment by k-gn** [comment]
관리자 주소 추가했습니다~

**Comment by ChanhyukPark-Tech** [comment]
Thx!!!!!
