### ISSUE TITLE
[기능] admin / 음식점 목록 필드추가

### ISSUE THREAD

**Issue by ChanhyukPark-Tech** [toppingskorea/toppings-server#26]
안녕하세요.

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/69495129/212471220-317674ea-5dbe-416a-84b9-3a9f670a09cb.png">

writer의 country값을 이용해야할 것 같은데 필드로 제공해주실 수 있나용?

**Comment by k-gn** [comment]
country 값 추가했습니다! 확인 감사합니다!

**Comment by ChanhyukPark-Tech** [comment]
thx for fast work!
