### ISSUE TITLE
[이슈] 리뷰 수정시 이미지 깨짐

### ISSUE THREAD

**Issue by ChanhyukPark-Tech** [toppingskorea/toppings-server#27]
저번에 프로필 사진 변경할때 있었던 이슈와 비슷합니다!

리뷰 처음에 등록하면 사진 잘 등록됩니다!
그 사진을 가지고, 리뷰 수정을 하기 위해 s3 url 보내면 깨진 이미지링크가 반환됩니다!😄

**Comment by k-gn** [comment]
해당 내용 일단 카톡방에 공유했습니다!

**Comment by ChanhyukPark-Tech** [comment]
thx for hard works🥳
