### ISSUE TITLE
[기능] 댓글 상세 조회하기에 음식점 이름 field 추가

### ISSUE THREAD

**Issue by ChanhyukPark-Tech** [toppingskorea/toppings-server#28]
<img width="372" alt="image" src="https://user-images.githubusercontent.com/69495129/213225544-aff9b18b-8045-414c-8cbf-46120b0ad35c.png">

해당 리뷰 상세 페이지에서 상단에 음식점 이름을 보여주기 위해서 

v1/review/11 (댓글 상세 조회하기)

의 field에 음식점 이름을 추가해주시면 좋겠습니다!

## 추가

사용자의 프로필 사진도 받아야할 것 같습니다!! 괜찮을까요!?

<img width="681" alt="image" src="https://user-images.githubusercontent.com/69495129/213235524-c7917681-5041-4f26-8848-33888fabb1c3.png">

**Comment by k-gn** [comment]
식당 이름과 유저 프로필 추가하였습니다! 확인 감사합니다! 👍👍

**Comment by ChanhyukPark-Tech** [comment]
thx!
