### ISSUE TITLE
[이슈] 리뷰 삭제 API 400 에러

### ISSUE THREAD

**Issue by ChanhyukPark-Tech** [toppingskorea/toppings-server#32]
저는 id:5, id:10 번 리뷰 소유자이며, 리뷰를 삭제 하기 위해서

/review/5 라는 주소로 delete method를 이용해서 삭제 요청을하였지만, 400 에러가 발생했습니다.
![image](https://user-images.githubusercontent.com/69495129/214236744-cf2905cf-f7a1-419f-a63a-414c28152bfe.png)

## 동영상 QA

https://user-images.githubusercontent.com/69495129/214236480-9f3f7d6a-059d-4671-b41a-82e5b48e2a22.mov

**Comment by k-gn** [comment]
댓글이 리젝된 댓글이였고, 댓글 목록 조회 시 리젝된 댓글을 제외시키는 조건이 빠져 발생한 이슈였습니다.

제외 시키는 조건 추가하였습니다~ 감사합니다!

**Comment by ChanhyukPark-Tech** [comment]
아하! 이해했습니다 좋네요 감사합니다🚀
