### ISSUE TITLE
[기능/어드민] 어드민 음식점 상세 조회 및 리뷰 상세 조회 필드 추가

### ISSUE THREAD

**Issue by ChanhyukPark-Tech** [toppingskorea/toppings-server#34]
어드민 음식점 상세 조회 및 리뷰 상세 조회할때 reject된건이라면 reject사유도 같이 보내주실 수 있나요?

![image](https://user-images.githubusercontent.com/69495129/214317962-999db4c3-7e54-4891-956c-ebb1f21e847b.png)

이건을 해결하기 위함입니다.

2개 API모두 해결되어야합니다!!

**Comment by k-gn** [comment]
리젝 사유 추가했습니다! N 인데 리젝 사유가 같이 안올 경우가 좀 있는데 리젝된 게시물이지만 리젝사유가 같이 등록되지 않은 데이터들이 좀 있어서 그냥 넘어가면 될 것 같습니다~
